# Generated by Django 3.2.19 on 2023-11-14 23:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0363_add_replay_payload_capture_config"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonOverride",
        ),
        migrations.DeleteModel(
            name="PersonOverrideMapping",
        ),
    ]
